.PHONY: run

run:
	rm -f answer_letter.aux && pdflatex answer_letter.tex && pdflatex answer_letter.tex && tput reset

.PHONY: clean

clean:
	rm -f *.aux *.lof *.log *.lot *.out *.toc *.pdf *.ist *.blg
